<?php
use AmazonAdvertisingApi\Table\AmazonAdsPortfolioTable;
use Micho\Utilities\DateTimeUtilities;
use AmazonAdvertisingApi\Table\SelectDateTable;
use App\ApplicationModul\Amazon\Model\AmazonMonthlySalesTable;
use AmazonAdvertisingApi\Table\AmazonAdsProfileTable;
?>

<article class="mx-1">

    <?php isset($profileMenu) ? require($profileMenu) : '' ?>
    <?php require('menu.phtml') ?>

    <section class="mx-2">
        <h2 class="text-center text-monospace">Amazon monthly sales unit sold - monthly sales table</h2>

        <div class="d-flex sticky-top bg-white" style="height: 90px">
            <div class="d-flex align-items-end m-2 p-1">
                <div class="btn-group" role="group">
                    <?php foreach ($menuProfile as $key => $menu) : ?>

                        <a class="btn btn-success <?= $profileCode === $menu ? 'active' : '' ?>"
                           href="amazon-monthly-sales/monthly-sales-pcs/<?= $menu ?>" title="<?= $key ?>" type="button">
                            <?= $key ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <table class="table table-hover table-sm table-sm table-bordered " style="overflow: visible;">
            <thead class="thead-light" style="position: sticky;top: 89px;">
            <tr class="">
                <?php foreach ($monthlySalesData['tableHeader'] as $key) : ?>
                    <th class="small font-weight-bold py-0 px-1 text-center" title="<?= AmazonMonthlySalesTable::DICTIONARY[$key]['description'] ?>"><?= AmazonMonthlySalesTable::DICTIONARY[$key]['title'] ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody class="">
            <?php foreach ($monthlySalesData['monthData'] as $monthData): ?>
                <?php foreach ($monthData['allData'] as $index => $report): ?>
                    <tr>
                        <?php foreach ($monthlySalesData['tableHeader'] as $key): ?>
                            <td class="py-0 px-1">
                                <?= ($key === SelectDateTable::SELECT_START_DATE || $key === SelectDateTable::SELECT_END_DATE)
                                    ? DateTimeUtilities::formatToShape($report[$key],'d.m.y')
                                    : (is_numeric($report[$key]) ? round($report[$key],2)
                                        : (($key === AmazonAdsPortfolioTable::NAME || $key === AmazonMonthlySalesTable::SKU) && !empty($productUrl)
                                            ? '<a href="' . $productUrl . '/' . ($key === AmazonMonthlySalesTable::SKU ? 'sku' : 'name' ) . '=' . $report[$key] . '">' . $report[$key] . '</a>'
                                            : ($key === AmazonAdsProfileTable::COUNTRY_CODE
                                                ? ($combine !== false ? '<b>'.$combine.'</b>' : '<b>'.$report[$key].'</b>')
                                                : $report[$key])))?>
                            </td>

                        <?php endforeach; ?>
                    </tr>
                <?php endforeach; ?>
                <tr class="text-nowrap" <?= isset($totalUrl) ? 'onclick="location.href=\'' . $totalUrl . '\'"' : '' ?>>
                    <?php foreach ($monthlySalesData['tableHeader'] as $key) : ?>
                        <th class="py-0 px-1">
                            <?= isset($monthData['totalData'][$key])
                                ? (($key === SelectDateTable::SELECT_START_DATE || $key === SelectDateTable::SELECT_END_DATE)
                                ? DateTimeUtilities::formatToShape($monthData['totalData'][$key],'d.m.y')
                                : (is_numeric($monthData['totalData'][$key]) ? round($monthData['totalData'][$key],2) : '')): ''?>

                        </th>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            <tr class="bg-dark"><td colspan = 100%></td></tr>
            <tr class="text-nowrap">
                <?php foreach ($monthlySalesData['tableHeader'] as $key) : ?>
                    <th class="py-0 px-1"><?= isset($monthlySalesData['allTotalData'][$key]) ? round($monthlySalesData['allTotalData'][$key],2) : '' ?></th>
                <?php endforeach; ?>

            </tr>
            </tbody>
        </table>
    </section>
    <footer>
    </footer>
    </div>
</article>

<script src="js/multipleSelect.js"></script>
<script src="js/clickSubmit.js"></script>

