<?php
use AmazonAdvertisingApi\Table\AmazonAdsPortfolioTable;
use Micho\Utilities\DateTimeUtilities;
use AmazonAdvertisingApi\Table\SelectDateTable;
use App\ApplicationModul\Amazon\Model\AmazonMonthlySalesTable;
use AmazonAdvertisingApi\Table\AmazonAdsProfileTable;
?>

<article class="mx-1">

    <?php isset($profileMenu) ? require($profileMenu) : '' ?>
    <?php require('menu.phtml') ?>

    <section class="mx-2">
        <h2 class="text-center text-monospace">Amazon monthly sales unit sold - monthly sales table</h2>

        <div class="d-flex sticky-top bg-white" style="height: 90px">
            <div class="d-flex align-items-end m-2 p-1">
                <div class="btn-group" role="group">
                    <?php foreach ($menuProfile as $key => $menu) : ?>

                        <a class="btn btn-success <?= $profileCode === $menu ? 'active' : '' ?>"
                           href="amazon-monthly-sales/monthly-sales-pcs/<?= $menu ?>" title="<?= $key ?>" type="button">
                            <?= $key ?>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>

        <table class="table table-hover table-sm table-bordered table-responsive" style="overflow: visible;">
            <thead class="thead-light" style="position: sticky;top: 89px;">
            <tr class="">
                <?php foreach ($monthlySalesPcsAllProduct['tableHeader'] as $product => $dates) : ?>
                    <th class="small font-weight-bold py-0 px-1 text-center">
                        <?= $product ?>
                    </th>
                    <?php foreach ($dates as $date) : ?>
                        <th class="small font-weight-bold py-0 px-1 text-center">
                            <?= DateTimeUtilities::yearMonth($date) ?>
                        </th>
                    <?php endforeach; ?>
                <?php endforeach; ?>
                <?php $header = array_shift($monthlySalesPcsAllProduct['tableHeader']) // odstranenie Product ?>
            </tr>
            </thead>
            <tbody class="">
            <?php foreach ($monthlySalesPcsAllProduct['monthData'] as $productName => $monthData): ?>
                <tr>
                    <td class="py-0 px-1">
                        <?= $productName ?>
                    </td>
                    <?php foreach ($header as $key => $data): ?>
                        <td><?= isset($monthData[$data]) ? $monthData[$data] : '' ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php endforeach; ?>
            <tr>
                <th class="py-0 px-1">
                    <?= $name = array_key_first($monthlySalesPcsAllProduct['monthTotalData']) ?>
                </th>
                <?php foreach ($header as $key => $data): ?>
                    <th><?= $monthlySalesPcsAllProduct['monthTotalData'][$name][$data] ?></th>
                <?php endforeach; ?>
            </tr>
            </tbody>
        </table>


        <?php if(isset($monthlySalesPcsIndividualProduct)) : ?>

            <?php foreach ($monthlySalesPcsIndividualProduct as $productName => $datas) : ?>

                <table class="table table-hover table-sm table-bordered table-responsive" style="overflow: visible;">
                    <thead class="thead-light" style="position: sticky;top: 89px;">
                    <tr class="">
                        <?php foreach ($datas['tableHeader'] as $product => $dates) : ?>
                            <th class="small font-weight-bold py-0 px-1 text-center">
                                <?= $product ?>
                            </th>
                            <?php foreach ($dates as $date) : ?>
                                <th class="small font-weight-bold py-0 px-1 text-center">
                                    <?= DateTimeUtilities::yearMonth($date) ?>
                                </th>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                        <?php $header = array_shift($datas['tableHeader']) // odstranenie Product ?>
                    </tr>
                    </thead>
                    <tbody class="">
                    <?php foreach ($datas['monthData'] as $countryName => $monthData): ?>
                        <tr>
                            <td class="py-0 px-1">
                                <?= $countryName ?>
                            </td>
                            <?php foreach ($header as $key => $data): ?>
                                <td><?= isset($monthData[$data]) ? $monthData[$data] : '' ?></td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                    <tr>
                        <th class="py-0 px-1">
                            <?= $name = array_key_first($datas['monthTotalData']) ?>
                        </th>
                        <?php foreach ($header as $key => $data): ?>
                            <th><?= $datas['monthTotalData'][$name][$data] ?></th>
                        <?php endforeach; ?>
                    </tr>
                    </tbody>

                </table>

            <?php endforeach; ?>

        <?php endif; ?>


    </section>
    <footer>
    </footer>
    </div>
</article>

<script src="js/multipleSelect.js"></script>
<script src="js/clickSubmit.js"></script>

