

<article class="jumbotron bg-transparent text-monospace">
    <div class="container">
        <header >
            <h2 class="display-3">Oops! Page not found ...</h2>
        </header>
        <section>
            <strong>
                You were shown this page because the address you typed or clicked 
                on our website (<a class="text-nowrap" href=""><?= $domainName ?></a>) it's not <span class="text-nowrap">(or no longer is)</span> available.
            </strong>
        </section>
        <footer>

        </footer>
    </div>
</article>