
<?php
use App\ArticleModul\Model\ArticleManager;
?>

<section class="d-flex justify-content-center">
    <div class="row justify-content-center">

        <?php foreach ($applications as $application) : ?>

        <div class="col">
            <a href="article/info/amazon-ads" title="<?= $application[ArticleManager::TITLE] ?>" class="text-decoration-none text-dark">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column">
                        <h4 class="card-header bg-white"><?= $application[ArticleManager::TITLE] ?></h4>
                        <p class="card-title"><?= $application[ArticleManager::DESCRIPTION] ?></p>
                        <a href="<?= $application[ArticleManager::LINK] ?>" class="btn btn-outline-success w-100 mt-auto">Start</a>
                    </div>
                </div>
            </a>
        </div>


        <?php endforeach; ?>
    </div>

</section>
<hr class="my-1">
<footer>

</footer>



