
<?php
use Micho\Form\Form;
?>

<section class="d-flex justify-content-center">

    <form method="post" id="<?= $_form['form_id'] ?>" >
        <?= $_form['csrf'] ?>

            <div class="form-group">
                <?= $_form['old_password'] ?>
            </div>
            <div class="form-row justify-content-center">
                <div class="form-group m-1">
                    <?= $_form[Form::PASSWORD] ?>
                </div>
                <div class="form-group m-1 w-auto">
                    <?= $_form['password_again'] ?>
                </div>
            </div>
        </div>

        <div class="mt-3">
            <?= $_form['password-change-button'] ?>
        </div>

    </form>

</section>
<hr class="my-1">

<footer>

</footer>



