
<?php
use Micho\Form\Form;
use App\AccountModul\Model\PersonDetailTable;
?>

<section class="d-flex justify-content-center">

    <form method="post" id="<?= $_form['form_id'] ?>" class="align-self-center">
        <?= $_form['csrf'] ?>
        <?= $_form[PersonDetailTable::PERSON_DETAIL_ID] ?>
            <div class="form-row justify-content-center">
                <div class="form-group m-1">
                    <?= $_form[PersonDetailTable::NAME] ?>
                </div>
                <div class="form-group m-1">
                    <?= $_form[PersonDetailTable::LAST_NAME] ?>
                </div>
            </div>

            <div class="form-row justify-content-center">
                <div class="form-group m-1">
                    <?= $_form[\App\AccountModul\Model\UserTable::EMAIL] ?>
                </div>
                <div class="form-group m-1">
                    <?= $_form[PersonDetailTable::TEL] ?>
                </div>
            </div>
                <?= $_form['save-button'] ?>

    </form>

</section>
<hr class="my-1">
<footer>

</footer>



