<article class="jumbotron bg-transparent">
    <div class="container ">
        <div class="row border rounded">
            <header class="col-12 col-md-6 border rounded ">
                <h3 class="display-3 m-md-5 m-2 mb-3"><?= $title ?></h3>
            </header>

            <div class="col border rounded p-5">

                <?php require($subview . '.phtml')  ?>

            </div>

        </div>

    </div>
</article>



