
<?php use App\ArticleModul\Model\ArticleManager; ?>

<article class="jumbotron bg-transparent">
    <header class="py-4 text-center">
        <h1 class="display-3 container">Contact us</h1>
    </header>
    <section class="container">

        <div class="row">
            <!--
            <div class="col-12 col-md-6">
                <p class="m-2">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum sed nibh enim. Suspendisse fringilla
                    mauris ac nisi auctor, faucibus interdum metus vulputate.
                </p>
            </div>
            -->
            <div class="col d-flex justify-content-center">
                <div class="card m-1">
                    <div class="card-header">
                        <h6 class="card-title"><em>Contact</em></h6>
                    </div>
                    <div class="card-body">
                        <h6 class="card-title"><em>Contact</em></h6>
                        <span class="card-text text-nowrap">Tel. č.:
                            <a class="" href="tel:<?= $tel ?>"><?= $tel ?></a>
                        </span>
                        <span class="card-text text-nowrap">Email:
                            <a class="" href="mailto:<?= $email ?>"><?= $email ?></a>
                        </span>
                    </div>
                </div>
            </div>

        </div>

    </section>
    <footer>

    </footer>

</article>