<h4>Kontaktný Email so stránky: <a href="https://<?= $domena ?>"><?= $domenaNazov ?></a></h4>
<!-- Kontakt  Kontaktný formulár-->
<div class="center">
    <h5>Vaše kontaktné údaje a otázky:</h5>
    <table>
        <tr>
            <th>Meno:</th>
            <td><?= $emailData['meno'] ?></td>
        </tr>
        <tr>
            <th>Priezvisko:</th>
            <td><?= $emailData['priezvisko'] ?></td>
        </tr>
        <tr>
            <th>Email:</th>
            <td><a href="mailto:<?= $emailData['kontakt_email'] ?>"><?= $emailData['kontakt_email'] ?></a></td>
        </tr>

        <tr>
            <th>Telefón:</th>
            <td><a href="tel:<?= $emailData['tel'] ?>"><?= $emailData['tel'] ?></a></td>
        </tr>

        <tr>
            <th>Správa:</th>
            <td class="sprava"><?= $emailData['sprava'] ?></td>
        </tr>
    </table>
</div>
<!-- Kontakt informácie-->
<div>
    <h5>Naše kontaktné údaje:</h5>
    <table class="contact">
        <tr class="header-table">
            <td></td>
            <th class="text-left"><?= Settings::$domainName ?></th>
        </tr>
        <tr>
            <th>Tel. č.:</th>
            <td><a class="text-white" href="tel:<?= Settings::$tel ?>"><?= Settings::$tel ?></a></td>
        </tr>
        <tr>
            <th>Email:</th>
            <td><a class="text-white" href="mailto:<?= Settings::$email ?>"><?= Settings::$email ?></a></td>
        </tr>

        <?php foreach ($kontakty as $key => $kontakt) : ?>
            <tr class="header-table">
                <th><?= $key ?></th>
                <th class="text-left"><?= $kontakt['osoba'] ?></th>
            </tr>
            <tr>
                <th>Tel. č.:</th>
                <td><a class="text-white" href="tel:<?= $kontakt['tel'] ?>"><?= $kontakt['tel'] ?></a></td>
            </tr>
            <tr>
                <th>Email:</th>
                <td><a class="text-white" href="mailto:<?= $kontakt['email'] ?>"><?= $kontakt['email'] ?></a></td>
            </tr>

        <?php endforeach; ?>

    </table>
</div>
