
<div class="btn-group">
    <a class="btn btn-secondary" href="account/personal-information" title="Back">
        <i class="fas fa-long-arrow-alt-left" aria-hidden="true"></i>
    </a>
    <a class="font-weight-bold text-dark btn btn-light <?= $method === 'settings'? 'active' : '' ?>" href="app-management/settings">Settings</a>
    <a class="font-weight-bold text-dark btn btn-light <?= $method === 'products-data'? 'active' : '' ?>" href="app-management/products-data">Add new products data</a>
</div>
