<?php use App\ClanokModul\Model\ArticleManazer; ?>
<div class="row">
    <?php foreach ($menu as $m): ?>
        <div class="karty col-lg-<?= 12 / count($menu) ?> p-sm-1 p-2 m-sm-0 mx-2 <?= $trieda ?>">
            <a href="<?= $m['typ_url'] ?>/<?= $m[ArticleManazer::URL] ?>">
                <img class="card-img " src="obrazky/menu/<?= $m[ArticleManazer::URL] ?>.jpg" alt="<?= $m[ArticleManazer::TITLE] ?>">
                <div class="card-img-overlay d-flex flex-column justify-content-end text-center">
                    <h2 class="card-title karty-text-menu pl-2"><?= $m[ArticleManazer::TITLE] ?></h2>
                </div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
