<h4>Forgot password on <a href="https://<?= $domain ?>"><?= $domainName ?></a></h4>
<div class="center">
    <h6>Hello, on our website <a href="https://<?= $domain ?>"><?= $domainName ?></a>
        you requested to generate a new password.</h6>
    <p>The new login password for your account is:</p>
    <table>
        <tr>
            <th>Login E-mail:</th>
            <td><?= $email ?></td>
        </tr>
        <tr>
            <th>New password:</th>
            <td><?= $password ?></td>
        </tr>
    </table>
    <br>
    <p>You can change your password after logging in to <a href="https://<?= $domain ?>/">to this address</a></p>

</div>