<?php
use AmazonAdvertisingApi\Report\DataRaw;
use AmazonAdvertisingApi\Report\ConstRaw;
use AmazonAdvertisingApi\Table\SelectDateTable;
use Micho\Utilities\DateTimeUtilities;
use App\AccountModul\Model\UserTable;
use AmazonAdvertisingApi\Table\AmazonAdsProfileTable;

?>

<article class="mx-1">

    <?php isset($profileMenu) ? require($profileMenu) : '' ?>
    <?php require('menu.phtml') ?>

    <section class="mx-2">
        <h2 class="text-center text-monospace">Amazon Advertising - download</h2>

        <form class="" method="post" id="<?= $_formSelect['form_id'] ?>" disabled="disable">
            <?= $_formSelect['csrf'] ?>
            <div class="form-inline justify-content-center">

                <span class="m-1"><?= $_formSelect[DataRaw::START_DATE] ?></span>

                <span class="m-1"><?= $_formSelect[DataRaw::END_DATE] ?></span>

                <span class="m-1"><?= $_formSelect[DataRaw::REPORT_TYPE_ID] ?></span>

                <span class="m-1"><?= $_formSelect[DataRaw::TIME_UNIT] ?></span>

                <span class="m-1"><?= $_formSelect['send-request'] ?></span>

                <a class="btn btn-success text-white m-1 <?= $disabledCheck ? 'disabled' : '' ?>" <?= $disabledCheck ? '' : 'href="' . $currentUrl . '"' ?>>Check data</a>
                <a class="btn btn-success text-white m-1 <?= $disabledDownload ? 'disabled' : '' ?>" <?= $disabledDownload ? '' : 'href="amazon-ads/download-report/' . $profileId . '/' . $reportId . '"' ?>>Download data</a>
                <a class="btn btn-sm btn-outline-info mt-auto mb-1 small py-0" href="amazon-ads/download/<?= $profileId ?>">Restart downloading</a>
            </div>
        </form>

        <hr>
        <h4><u>Downloaded dates</u></h4>
        <?php foreach ($dateSpTargSearch['dates'] as $key => $spTypeData): ?>
            <strong><?= array_flip(ConstRaw::REPORT_TYPE_ID)[$key] ?></strong>
            <?php if (is_array($spTypeData)) : ?>
                <?php foreach ($spTypeData as $date): ?>
                    <?php $niceDate = DateTimeUtilities::formatToShape($date[SelectDateTable::SELECT_START_DATE],'j.m.y')
                        . ' -> ' . DateTimeUtilities::formatToShape($date[SelectDateTable::SELECT_END_DATE],'j.m.y') ?>
                    <span class="btn btn-sm btn-success m-0"><?= $niceDate ?>
                        <?= DialogHelper::createDeleteDialog($date[SelectDateTable::SELECT_DATE_ID] . '_' . $key,
                            'amazon-ads/delete-report/' . $key . '/' . $date[SelectDateTable::SELECT_DATE_ID] . '/' . $dateSpTargSearch[UserTable::USER_ID] . '/' . $dateSpTargSearch[AmazonAdsProfileTable::PROFILE_ID],
                            'Do you really wish to delete the selected report? <span class="btn btn-sm btn-success m-0">' . $niceDate) . '</span>' ?>
                    </span>
                <?php endforeach; ?>
            <?php endif; ?>
            <hr>
        <?php endforeach; ?>

    </section>
    <footer>
    </footer>
    </div>
</article>