
<div class="btn-group">
    <a class="btn btn-secondary" href="account/application" title="Back">
        <i class="fas fa-long-arrow-alt-left" aria-hidden="true"></i>
    </a>
    <a class="font-weight-bold text-dark btn btn-light <?= $method === 'download'? 'active' : '' ?>" href="amazon-ads/download/<?= $profile ?>">Download</a>
    <a class="font-weight-bold text-dark btn btn-light <?= $method === 'statistics'? 'active' : '' ?>" href="amazon-ads/statistics/<?= $profile ?>">Statistics</a>
</div>
